// proyectos
export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO';
export const OBTENER_PROYECTO = 'OBTENER_PROYECTO';
export const MOSTRAR_ERROR = 'MOSTRAR_ERROR';
export const OBTENER_PROYECTO_ACTUAL = 'OBTENER_PROYECTO_ACTUAL';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';

// tareas

export const FILTRAR_TAREAS = 'FILTRAR_TAREAS';
export const AGREGAR_TAREAS = 'AGREGAR_TAREAS';
export const ERROR_FORMULARIO = 'ERROR_FORMULARIO';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const ESTADO_TAREA = 'ESTADO_TAREA';
export const TAREA_ACTUAL = 'TAREA_ACTUAL';
export const TAREAS_ACTUALES = 'TAREAS_ACTUALES';
export const EDITAR_TAREAS = 'EDITAR_TAREAS';